apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ext-nhs-auth-app
  description: External NHS API components
  labels:
    category: external
    sub-category: nhs-apps
  annotations:
    github.com/project-slug: backstage-demo-26/backstage-custom-code/ext-nhs-apps/ext-nhs-auth-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  # system: ext-nhs-apps
  lifecycle: production
  providesApis:
    - ext-nhs-access-token-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ext-nhs-access-token-api
  description: NHS Application Restricted Access Token interface
spec:
  type: openapi
  lifecycle: production
  owner: development
  definition:
    $text: ./openapi/ext-auth-app-restricted.yaml

