site_name: 'nhs-access-token-app'
site_description: 'Main documentation for the External NHS Authentication API'
repo_url: https://github.com/backstage-demo-26/ext-nhs-apis/ext-nhs-auth-api
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'