site_name: 'photia-nhs-pds-app'
site_description: 'Main documentation for the Photia NHS PDS wrapper API'
repo_url: https://github.com/backstage-demo-26/photia-nhs-apps/photia-nhs-pds-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'