apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ext-nhs-pds-app
  description: External NHS PDS API components
  labels:
    category: external
    sub-category: nhs-api
  annotations:
    github.com/project-slug: backstage-demo-26/backstage-custom-code/ext-nhs-apps/ext-nhs-pds-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  system: pds-trace-ui-flow
  lifecycle: production
  providesApis:
    - ext-nhs-pds-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ext-nhs-pds-api
  description: NHS API for PDS tracing
spec:
  type: openapi
  lifecycle: production
  owner: development
  definition:
    $text: ./openapi/ext-pds-fhir.yaml
