# 1. The Overarching System Boundary Grouping
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pds-trace-ui-flow
  description: PDS trace UI flow
  annotations:
    github.com/project-slug: backstage-demo-26/backstage-custom-code/service-defs/systems
    backstage.io/techdocs-ref: dir:.
spec:
  owner: architecture