apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rapport-ui-banner
  description: Rapport UI Banner component
  labels:
    category: rapport-ui
    sub-category: rapport-ui-banner
  annotations:
    github.com/project-slug: backstage-demo-26/backstage-custom-code/rapport-ui/rapport-ui-banner
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  system: pds-trace-ui-flow
  lifecycle: production
  providesApis:
    - rapport-ui-banner-pds-trace
    - rapport-ui-banner-demographics
  consumesApis: 
    - photia-nhs-pds-api     

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rapport-ui-banner-pds-trace
  description: Photia NHS API for PDS tracing
spec:
  type: openapi
  lifecycle: production
  owner: development
  consumesApis: 
    - photia-nhs-pds-api 
  definition:
    $text: ./openapi/rapport-ui-banner-pds-trace.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rapport-ui-banner-demographics
  description: Photia NHS API for PDS tracing
spec:
  type: openapi
  lifecycle: production
  owner: development
  definition:
    $text: ./openapi/rapport-ui-banner-demographics.yaml
