apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monorepo-components-root
  description: Automatically aggregates all nested component yaml files via glob loops
spec:
  targets:
    # - ./*/catalog-info.yaml
    # Single asterisk tracks all immediate subfolders
    # - ./*/*/catalog-info.yaml
    # Double asterisk recursively crawls deeply nested folders
    - ./**/catalog-info.yaml
    - ./systems/catalog-info-*.yaml
